name: prac-exercise1
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: run-lint-test
        run: |
          cd 04-Practice-Project
          npm run lint
      - name: run-tests
        run: |
          cd 04-Practice-Project
          npm run test
      - name: build-project
        run: |
          cd 04-Practice-Project
          npm run build
      - name: deploy-project
        run: echo "deploying ..."
