name: prac-exercise1
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: run-lint-test
        run: |
          cd 04-Practice-Project
          npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: run-tests
        run: |
          cd 04-Practice-Project
          npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: build-project
        run: |
          cd 04-Practice-Project
          npm run build
      - name: deploy-project
        run: echo "deploying ..."
