name: prac-exercise1
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: run-lint-test
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: run-tests
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get-the-code
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install-dependencies
        run: |
          cd 04-Practice-Project
          npm ci
      - name: build-project
        run: npm run build
      - name: deploy-project
        run: echo "deploying ..."
